# This is the neoforge.mods.toml file for Sanity: Descent Into Madness.
# See the full specification at https://docs.neoforged.net/docs/mods/toml
modLoader="javafml"

loaderVersion="${loader_version_range}"

license="${mod_license}"

issueTrackerURL="https://github.com/whaleghost/SanityDescentIntoMadnessRenewed/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://github.com/whaleghost/SanityDescentIntoMadnessRenewed"
logoFile="sanitydim512.png"
credits="croissantnova, toujourspareil, Zapsplat"
authors="whaleghost"
description='''Brings the sanity mechanic from Don't Starve into Minecraft. Refactored from croissantnova/SanityDescentIntoMadness.'''

[[mixins]]
config="sanitydimr.mixins.json"

[[dependencies.${mod_id}]]
    modId="geckolib"
    type="required"
    versionRange="[4.7,)"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
